// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module aes_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 6
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output aes_reg_pkg::aes_reg2hw_t reg2hw,  // Write
    input aes_reg_pkg::aes_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import aes_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic               reg_we;
  logic               reg_re;
  logic [BlockAw-1:0] reg_addr;
  logic [     DW-1:0] reg_wdata;
  logic [    DBW-1:0] reg_be;
  logic [     DW-1:0] reg_rdata;
  logic               reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] plaintext_0_qs;
  logic [31:0] plaintext_0_wd;
  logic plaintext_0_we;
  logic [31:0] plaintext_1_qs;
  logic [31:0] plaintext_1_wd;
  logic plaintext_1_we;
  logic [31:0] plaintext_2_qs;
  logic [31:0] plaintext_2_wd;
  logic plaintext_2_we;
  logic [31:0] plaintext_3_qs;
  logic [31:0] plaintext_3_wd;
  logic plaintext_3_we;
  logic [31:0] key_0_qs;
  logic [31:0] key_0_wd;
  logic key_0_we;
  logic [31:0] key_1_qs;
  logic [31:0] key_1_wd;
  logic key_1_we;
  logic [31:0] key_2_qs;
  logic [31:0] key_2_wd;
  logic key_2_we;
  logic [31:0] key_3_qs;
  logic [31:0] key_3_wd;
  logic key_3_we;
  logic control_qs;
  logic control_wd;
  logic control_we;
  logic status_busy_qs;
  logic status_done_qs;
  logic [31:0] ciphertext_0_qs;
  logic [31:0] ciphertext_1_qs;
  logic [31:0] ciphertext_2_qs;
  logic [31:0] ciphertext_3_qs;

  // Register instances
  // R[plaintext_0]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_plaintext_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(plaintext_0_we),
      .wd(plaintext_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.plaintext_0.q),

      // to register interface (read)
      .qs(plaintext_0_qs)
  );


  // R[plaintext_1]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_plaintext_1 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(plaintext_1_we),
      .wd(plaintext_1_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.plaintext_1.q),

      // to register interface (read)
      .qs(plaintext_1_qs)
  );


  // R[plaintext_2]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_plaintext_2 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(plaintext_2_we),
      .wd(plaintext_2_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.plaintext_2.q),

      // to register interface (read)
      .qs(plaintext_2_qs)
  );


  // R[plaintext_3]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_plaintext_3 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(plaintext_3_we),
      .wd(plaintext_3_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.plaintext_3.q),

      // to register interface (read)
      .qs(plaintext_3_qs)
  );


  // R[key_0]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_key_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(key_0_we),
      .wd(key_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.key_0.q),

      // to register interface (read)
      .qs(key_0_qs)
  );


  // R[key_1]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_key_1 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(key_1_we),
      .wd(key_1_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.key_1.q),

      // to register interface (read)
      .qs(key_1_qs)
  );


  // R[key_2]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_key_2 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(key_2_we),
      .wd(key_2_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.key_2.q),

      // to register interface (read)
      .qs(key_2_qs)
  );


  // R[key_3]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_key_3 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(key_3_we),
      .wd(key_3_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.key_3.q),

      // to register interface (read)
      .qs(key_3_qs)
  );


  // R[control]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_we),
      .wd(control_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(reg2hw.control.qe),
      .q (reg2hw.control.q),

      // to register interface (read)
      .qs(control_qs)
  );


  // R[status]: V(False)

  //   F[busy]: 0:0
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_status_busy (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.status.busy.de),
      .d (hw2reg.status.busy.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.status.busy.q),

      // to register interface (read)
      .qs(status_busy_qs)
  );


  //   F[done]: 1:1
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_status_done (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.status.done.de),
      .d (hw2reg.status.done.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.status.done.q),

      // to register interface (read)
      .qs(status_done_qs)
  );


  // R[ciphertext_0]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_ciphertext_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.ciphertext_0.de),
      .d (hw2reg.ciphertext_0.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.ciphertext_0.q),

      // to register interface (read)
      .qs(ciphertext_0_qs)
  );


  // R[ciphertext_1]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_ciphertext_1 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.ciphertext_1.de),
      .d (hw2reg.ciphertext_1.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.ciphertext_1.q),

      // to register interface (read)
      .qs(ciphertext_1_qs)
  );


  // R[ciphertext_2]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_ciphertext_2 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.ciphertext_2.de),
      .d (hw2reg.ciphertext_2.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.ciphertext_2.q),

      // to register interface (read)
      .qs(ciphertext_2_qs)
  );


  // R[ciphertext_3]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_ciphertext_3 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.ciphertext_3.de),
      .d (hw2reg.ciphertext_3.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.ciphertext_3.q),

      // to register interface (read)
      .qs(ciphertext_3_qs)
  );




  logic [13:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == AES_PLAINTEXT_0_OFFSET);
    addr_hit[1] = (reg_addr == AES_PLAINTEXT_1_OFFSET);
    addr_hit[2] = (reg_addr == AES_PLAINTEXT_2_OFFSET);
    addr_hit[3] = (reg_addr == AES_PLAINTEXT_3_OFFSET);
    addr_hit[4] = (reg_addr == AES_KEY_0_OFFSET);
    addr_hit[5] = (reg_addr == AES_KEY_1_OFFSET);
    addr_hit[6] = (reg_addr == AES_KEY_2_OFFSET);
    addr_hit[7] = (reg_addr == AES_KEY_3_OFFSET);
    addr_hit[8] = (reg_addr == AES_CONTROL_OFFSET);
    addr_hit[9] = (reg_addr == AES_STATUS_OFFSET);
    addr_hit[10] = (reg_addr == AES_CIPHERTEXT_0_OFFSET);
    addr_hit[11] = (reg_addr == AES_CIPHERTEXT_1_OFFSET);
    addr_hit[12] = (reg_addr == AES_CIPHERTEXT_2_OFFSET);
    addr_hit[13] = (reg_addr == AES_CIPHERTEXT_3_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(AES_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(AES_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(AES_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(AES_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(AES_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(AES_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(AES_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(AES_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(AES_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(AES_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(AES_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(AES_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(AES_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(AES_PERMIT[13] & ~reg_be)))));
  end

  assign plaintext_0_we = addr_hit[0] & reg_we & !reg_error;
  assign plaintext_0_wd = reg_wdata[31:0];

  assign plaintext_1_we = addr_hit[1] & reg_we & !reg_error;
  assign plaintext_1_wd = reg_wdata[31:0];

  assign plaintext_2_we = addr_hit[2] & reg_we & !reg_error;
  assign plaintext_2_wd = reg_wdata[31:0];

  assign plaintext_3_we = addr_hit[3] & reg_we & !reg_error;
  assign plaintext_3_wd = reg_wdata[31:0];

  assign key_0_we = addr_hit[4] & reg_we & !reg_error;
  assign key_0_wd = reg_wdata[31:0];

  assign key_1_we = addr_hit[5] & reg_we & !reg_error;
  assign key_1_wd = reg_wdata[31:0];

  assign key_2_we = addr_hit[6] & reg_we & !reg_error;
  assign key_2_wd = reg_wdata[31:0];

  assign key_3_we = addr_hit[7] & reg_we & !reg_error;
  assign key_3_wd = reg_wdata[31:0];

  assign control_we = addr_hit[8] & reg_we & !reg_error;
  assign control_wd = reg_wdata[0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = plaintext_0_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = plaintext_1_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = plaintext_2_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = plaintext_3_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = key_0_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = key_1_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = key_2_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = key_3_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[0] = control_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[0] = status_busy_qs;
        reg_rdata_next[1] = status_done_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = ciphertext_0_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = ciphertext_1_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = ciphertext_2_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[31:0] = ciphertext_3_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module aes_reg_top_intf #(
    parameter  int AW = 6,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output aes_reg_pkg::aes_reg2hw_t reg2hw,  // Write
    input aes_reg_pkg::aes_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  aes_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


