// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package aes_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [31:0] q;} aes_reg2hw_plaintext_0_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_plaintext_1_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_plaintext_2_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_plaintext_3_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_key_0_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_key_1_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_key_2_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_key_3_reg_t;

  typedef struct packed {
    logic q;
    logic qe;
  } aes_reg2hw_control_reg_t;

  typedef struct packed {
    struct packed {logic q;} busy;
    struct packed {logic q;} done;
  } aes_reg2hw_status_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_ciphertext_0_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_ciphertext_1_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_ciphertext_2_reg_t;

  typedef struct packed {logic [31:0] q;} aes_reg2hw_ciphertext_3_reg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } busy;
    struct packed {
      logic d;
      logic de;
    } done;
  } aes_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } aes_hw2reg_ciphertext_0_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } aes_hw2reg_ciphertext_1_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } aes_hw2reg_ciphertext_2_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } aes_hw2reg_ciphertext_3_reg_t;

  // Register -> HW type
  typedef struct packed {
    aes_reg2hw_plaintext_0_reg_t plaintext_0;  // [387:356]
    aes_reg2hw_plaintext_1_reg_t plaintext_1;  // [355:324]
    aes_reg2hw_plaintext_2_reg_t plaintext_2;  // [323:292]
    aes_reg2hw_plaintext_3_reg_t plaintext_3;  // [291:260]
    aes_reg2hw_key_0_reg_t key_0;  // [259:228]
    aes_reg2hw_key_1_reg_t key_1;  // [227:196]
    aes_reg2hw_key_2_reg_t key_2;  // [195:164]
    aes_reg2hw_key_3_reg_t key_3;  // [163:132]
    aes_reg2hw_control_reg_t control;  // [131:130]
    aes_reg2hw_status_reg_t status;  // [129:128]
    aes_reg2hw_ciphertext_0_reg_t ciphertext_0;  // [127:96]
    aes_reg2hw_ciphertext_1_reg_t ciphertext_1;  // [95:64]
    aes_reg2hw_ciphertext_2_reg_t ciphertext_2;  // [63:32]
    aes_reg2hw_ciphertext_3_reg_t ciphertext_3;  // [31:0]
  } aes_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    aes_hw2reg_status_reg_t status;  // [135:132]
    aes_hw2reg_ciphertext_0_reg_t ciphertext_0;  // [131:99]
    aes_hw2reg_ciphertext_1_reg_t ciphertext_1;  // [98:66]
    aes_hw2reg_ciphertext_2_reg_t ciphertext_2;  // [65:33]
    aes_hw2reg_ciphertext_3_reg_t ciphertext_3;  // [32:0]
  } aes_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] AES_PLAINTEXT_0_OFFSET = 6'h0;
  parameter logic [BlockAw-1:0] AES_PLAINTEXT_1_OFFSET = 6'h4;
  parameter logic [BlockAw-1:0] AES_PLAINTEXT_2_OFFSET = 6'h8;
  parameter logic [BlockAw-1:0] AES_PLAINTEXT_3_OFFSET = 6'hc;
  parameter logic [BlockAw-1:0] AES_KEY_0_OFFSET = 6'h10;
  parameter logic [BlockAw-1:0] AES_KEY_1_OFFSET = 6'h14;
  parameter logic [BlockAw-1:0] AES_KEY_2_OFFSET = 6'h18;
  parameter logic [BlockAw-1:0] AES_KEY_3_OFFSET = 6'h1c;
  parameter logic [BlockAw-1:0] AES_CONTROL_OFFSET = 6'h20;
  parameter logic [BlockAw-1:0] AES_STATUS_OFFSET = 6'h24;
  parameter logic [BlockAw-1:0] AES_CIPHERTEXT_0_OFFSET = 6'h28;
  parameter logic [BlockAw-1:0] AES_CIPHERTEXT_1_OFFSET = 6'h2c;
  parameter logic [BlockAw-1:0] AES_CIPHERTEXT_2_OFFSET = 6'h30;
  parameter logic [BlockAw-1:0] AES_CIPHERTEXT_3_OFFSET = 6'h34;

  // Register index
  typedef enum int {
    AES_PLAINTEXT_0,
    AES_PLAINTEXT_1,
    AES_PLAINTEXT_2,
    AES_PLAINTEXT_3,
    AES_KEY_0,
    AES_KEY_1,
    AES_KEY_2,
    AES_KEY_3,
    AES_CONTROL,
    AES_STATUS,
    AES_CIPHERTEXT_0,
    AES_CIPHERTEXT_1,
    AES_CIPHERTEXT_2,
    AES_CIPHERTEXT_3
  } aes_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] AES_PERMIT[14] = '{
      4'b1111,  // index[ 0] AES_PLAINTEXT_0
      4'b1111,  // index[ 1] AES_PLAINTEXT_1
      4'b1111,  // index[ 2] AES_PLAINTEXT_2
      4'b1111,  // index[ 3] AES_PLAINTEXT_3
      4'b1111,  // index[ 4] AES_KEY_0
      4'b1111,  // index[ 5] AES_KEY_1
      4'b1111,  // index[ 6] AES_KEY_2
      4'b1111,  // index[ 7] AES_KEY_3
      4'b0001,  // index[ 8] AES_CONTROL
      4'b0001,  // index[ 9] AES_STATUS
      4'b1111,  // index[10] AES_CIPHERTEXT_0
      4'b1111,  // index[11] AES_CIPHERTEXT_1
      4'b1111,  // index[12] AES_CIPHERTEXT_2
      4'b1111  // index[13] AES_CIPHERTEXT_3
  };

endpackage

